name: Run unit tests on PR
on:
  push
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: PHP ${{ matrix.php }} WP ${{ matrix.wp }}
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.wp == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0' ]
        wp: [ "latest" ]
        include:
          - wp: nightly
            php: '7.4'
          - wp: '5.9'
            php: 7.2
          - wp: '5.8'
            php: 7.2
    services:
      database:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: mysql
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Get cached composer directories
          uses: actions/cache@v2
          with:
            path: ~/.composer/cache
            key: ${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            - name: Setup and install composer
              run: |
                composer install --prefer-dist
                composer require --dev --update-with-dependencies --prefer-dist roots/wordpress="${{ matrix.wp == 'latest' && '*' || matrix.wp }} || *" wp-phpunit/wp-phpunit="${{ matrix.wp == 'latest' && '*' || matrix.wp }} || *"
            - name: Run unit tests
              run: composer test
              env:
                MYSQL_DATABASE: wordpress
                WP_TESTS_DB_PASS: root
                WP_TESTS_DB_HOST: "127.0.0.1"